image: docker-registry.hexun.com/hexunzq/docker:1.8.3
stages:
  - clean
  - package
  - deploy
clean:
  stage: clean
  script:
    - mkdir -p ../${CI_PROJECT_ID}${CI_BUILD_REF_NAME}
    - rm -rf ../${CI_PROJECT_ID}${CI_BUILD_REF_NAME}/*
  only:
    - master
package:
  stage: package
  script:
    - mvn clean package -DskipTests=true -
    - find .|grep war|xargs -i -t mv {} ../${CI_PROJECT_ID}${CI_BUILD_REF_NAME}/
    - find .|grep jar|xargs -i -t mv {} ../${CI_PROJECT_ID}${CI_BUILD_REF_NAME}/
  only:
    - master
deploy-web-api:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - echo "deploy webapi"
    - sh ./deploy/webapi.sh

deploy-console:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - echo "deploy console"
    - sh ./deploy/console.sh